Es6 - Awesome Books
tawakuliKH/Awesome-Books_Es6 pull request #2
Opened 2023-05-01 19:12 UTC by tawakuliKH

In this branch:

- [ ] Use ES6 modules and format in the classes

2023-05-01 19:24 UTC, aamirkhan2478 reviewed
Hi @tawakuliKH , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that hasn't a descriptive PR summary kindly add descriptive PR summary check below :point_down: example of descriptive PR summary :+1: 

![219520522-f0a8c7ba-b272-4a26-81c7-c233913f9c1e](https://user-images.githubusercontent.com/45226848/235515234-edb67991-7545-4a8c-ab00-3f591cc30ee8.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-01 20:53 UTC, Munsa1 requested changes
Hi @tawakuliKH, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Created Descriptive PR According to Previously Required Changes :heavy_check_mark: 
Managed to Maintain Functionality of App After Refactor :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-01 20:53 UTC, Munsa1 commented on README.md
> +
- [ ] Kindly remove commented code as it  it makes your readme codebase harder to read

2023-05-01 20:53 UTC, Munsa1 commented on README.md
> +--->
- [ ] Again here it would be nice to remove commented lines from your Readme file, for  cleaner codebase

2023-05-01 20:53 UTC, Munsa1 commented on README.md
> + -->
- [ ] Again here it would be nice to remove commented lines from your Readme file, for  cleaner codebase

2023-05-01 20:53 UTC, Munsa1 commented on README.md
> +- Twitter: [@twitterhandle](https://twitter.com/twitterhandle)
- [ ] Kindly fix this broken link as it leads nowhere

2023-05-01 20:53 UTC, Munsa1 commented on modules/BookCollectClass.js
> +  }
- [ ] Its a requirement for this milestone to refactor functions to use Arrow Syntax. Kindly do so
![image](https://user-images.githubusercontent.com/81932478/235524800-13e319d4-5b5a-4b48-9f5d-14faba74870e.png)

2023-05-01 20:53 UTC, Munsa1 commented on modules/BookCollectClass.js
> +  }
- [ ] The point of this milestone is to modularize your code as much as possible. You could achieve more of this by creating a separate module for saving to localStorage. You can then import the module and use the function here and for the `addBook` function as well. Kindly do so

2023-05-02 10:08 UTC, LionRouge1 approved these changes
Hi @tawakuliKH, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

![done](https://media.giphy.com/media/a5llhdWKMOIfneMCpB/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-05-02 10:10 UTC, merged